name = "THBSplines"
uuid = "99016233-ed97-49a6-867d-9b1fce6b5467"
authors = ["henrij22 <96132706+henrij22@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
